# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 23:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/complaint-files/', verbose_name='Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('clean_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receipt', models.DateField(verbose_name='Date of Receipt in MIS')),
                ('mis_register_sno', models.CharField(max_length=50, verbose_name='MIS Dak Register S.No')),
                ('petition_id_no', models.CharField(max_length=200, verbose_name='Petition ID No')),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'CLEARED'), (2, 'RETURNED')], default=0)),
                ('id_date', models.DateField()),
                ('vip_name', models.CharField(blank=True, max_length=100, verbose_name='Name of MP/VIP')),
                ('vip_appointment', models.CharField(blank=True, max_length=50, verbose_name='Appointment of MP/ VIP')),
                ('subject', models.CharField(max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('fwd_date', models.DateField(auto_now_add=True)),
                ('petitioner_name', models.CharField(blank=True, max_length=100, verbose_name='Name of Petitioner')),
                ('petition_date', models.DateField(null=True)),
                ('reply_letter_no', models.CharField(blank=True, max_length=50, verbose_name='Reply Letter No')),
                ('date_of_reply', models.DateField(null=True)),
                ('reply_letter', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/reply-letters')),
                ('returned_date', models.DateField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Category')),
                ('fwd_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.Complaint', verbose_name='Complaint'),
        ),
    ]
