# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='vip_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name of MP/VIP'),
        ),
    ]
