# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20170216_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='petitioner_name',
            field=models.TextField(blank=True, verbose_name='Name of Petitioner'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='remarks',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reply_letter_no',
            field=models.TextField(blank=True, verbose_name='Reply Letter No'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='vip_appointment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Appointment of MP/ VIP'),
        ),
    ]
